# Generated by Django 5.0 on 2023-12-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='behaviors',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='coat_length',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='pet_name',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='size',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='animal',
            name='behavior',
            field=models.CharField(choices=[('Digging', 'Digging'), ('Eating Poop', 'Eating Poop'), ('Head Pressing', 'Head Pressing'), ('Scooting', 'Scooting'), ('Yawning', 'Yawning'), ('Biting', 'Biting'), ('Circling', 'Circling')], default='default_behavior', max_length=255),
        ),
        migrations.AddField(
            model_name='animal',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('brown', 'Brown'), ('white', 'White'), ('grey', 'Grey'), ('red', 'Red'), ('blue', 'Blue'), ('gold', 'Gold'), ('cream', 'Cream')], default='kalo', max_length=255),
        ),
        migrations.AddField(
            model_name='animal',
            name='name',
            field=models.CharField(default='pet', max_length=255),
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven')], default='default_behavior'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(choices=[('German Shepherd', 'German Shepherd'), ('Bulldog', 'Bulldog'), ('French Bulldog', 'French Bulldog'), ('Golden Retriever', 'Golden Retriever'), ('Chow Chow', 'Chow Chow')], default='streetdog', max_length=255),
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.CharField(choices=[('10-20 small lbs', '1 Queen Pillow'), ('30-40 lbs medium', '2 Standard Pillows'), ('50-60 lbs large', '2 King Pillows'), ('70-80 lbs xl', '3 King Pillows')], default='default_behavior', max_length=255),
        ),
    ]
