# Generated by Django 5.0 on 2023-12-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_animal_behaviors_remove_animal_coat_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='animal_images/'),
        ),
    ]
