# Generated by Django 5.0 on 2023-12-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('dog_breed', models.CharField(max_length=100)),
                ('small_dog', models.BooleanField(default=False)),
                ('medium_dog', models.BooleanField(default=False)),
                ('large_dog', models.BooleanField(default=False)),
                ('experience', models.CharField(max_length=20)),
                ('reason_for_adoption', models.TextField()),
                ('terms_accepted', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Adoption',
        ),
    ]
