# Generated by Django 3.2.10 on 2024-01-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_animal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='id',
        ),
        migrations.AddField(
            model_name='animal',
            name='pet_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
