# Generated by Django 5.0 on 2023-12-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_dogadoption_delete_adoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogadoption',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='dogadoption',
            name='large_dog',
        ),
        migrations.RemoveField(
            model_name='dogadoption',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='dogadoption',
            name='medium_dog',
        ),
        migrations.RemoveField(
            model_name='dogadoption',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='dogadoption',
            name='small_dog',
        ),
        migrations.RemoveField(
            model_name='dogadoption',
            name='terms_accepted',
        ),
        migrations.AddField(
            model_name='dogadoption',
            name='name',
            field=models.CharField(default='hari', max_length=10),
        ),
        migrations.AddField(
            model_name='dogadoption',
            name='telephone',
            field=models.CharField(default='9852182125', max_length=20),
        ),
        migrations.AlterField(
            model_name='dogadoption',
            name='experience',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('experienced', 'Experienced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dogadoption',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dogadoption',
            name='zip_code',
            field=models.CharField(max_length=20),
        ),
    ]
