# Generated by Django 3.2.10 on 2024-01-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20240105_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='pet_id',
            field=models.AutoField(default=999, primary_key=True, serialize=False),
        ),
    ]
