# Generated by Django 3.2.10 on 2024-01-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_animal_pet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='pet_id',
            new_name='id',
        ),
    ]
