# Generated by Django 3.2.10 on 2024-01-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_pet_id_animal_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='id',
            new_name='pet_id',
        ),
    ]
