# Generated by Django 5.0 on 2024-01-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_animal_pet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='kitty', max_length=255)),
                ('color', models.CharField(choices=[('black', 'Black'), ('brown', 'Brown'), ('white', 'White'), ('grey', 'Grey'), ('tabby', 'tabby'), ('Calico', 'Calico')], default='Tabby', max_length=255)),
                ('age', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven')], default='Unknown')),
                ('weight', models.CharField(choices=[('10-20 small lbs', 'Small'), ('30-40 lbs medium', 'Medium'), ('50-60 lbs large', 'large')], default='default_behavior', max_length=255)),
                ('Friendliness', models.CharField(choices=[('Outgoing', 'Outgoing'), ('very social', 'very social'), ('Reserved', 'Reserved')], default='medium', max_length=255)),
                ('image', models.ImageField(default='default_image.jpg', max_length=250, null=True, upload_to='animal_images/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Animal',
            new_name='Animal_dog',
        ),
    ]
