# Generated by Django 5.0 on 2024-01-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_cats_rename_animal_animal_dog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birds',
            fields=[
                ('bird_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Feather', max_length=255)),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('white', 'White'), ('black', 'Black')], default='Colorful', max_length=255)),
                ('species', models.CharField(choices=[('parrot', 'Parrot'), ('canary', 'Canary'), ('budgie', 'Budgie'), ('finch', 'Finch'), ('cockatoo', 'Cockatoo')], default='Parrot', max_length=255)),
                ('age', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven')], default='Unknown')),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=255)),
                ('friendliness', models.CharField(choices=[('Friendly', 'Friendly'), ('Social', 'Social'), ('Reserved', 'Reserved')], default='Friendly', max_length=255)),
                ('image', models.ImageField(default='default_bird_image.jpg', max_length=250, null=True, upload_to='bird_images/')),
            ],
        ),
    ]
