# Generated by Django 5.0 on 2024-01-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_donation_data_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='other_animals',
            fields=[
                ('animal_id', models.AutoField(primary_key=True, serialize=False)),
                ('animal', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=1)),
                ('about_it', models.TextField()),
                ('image', models.ImageField(default='default_image.jpg', max_length=250, null=True, upload_to='pet_images/')),
            ],
        ),
    ]
