# Generated by Django 5.0 on 2024-01-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_user_profile_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='hari', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(default='9852182125', max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('petname', models.CharField(max_length=10)),
                ('petgender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('dogBreed', models.CharField(max_length=100)),
                ('experience', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('experienced', 'Experienced')], max_length=20)),
                ('reason_for_adoption', models.TextField()),
            ],
        ),
    ]
