# Generated by Django 5.0 on 2024-01-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_animal_dog_dog_description_animal_dog_dog_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birds',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('brown', 'Brown'), ('white', 'White'), ('grey', 'Grey'), ('Tabby', 'Tabby')], default='Grey', max_length=255),
        ),
        migrations.AlterField(
            model_name='birds',
            name='name',
            field=models.CharField(default='Bird', max_length=255),
        ),
    ]
