# Generated by Django 3.2.10 on 2024-01-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_birds_color_alter_birds_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation_data',
            name='about_species',
        ),
        migrations.RemoveField(
            model_name='donation_data',
            name='animal_Description',
        ),
        migrations.RemoveField(
            model_name='donation_data',
            name='animal_History',
        ),
        migrations.AddField(
            model_name='other_animals',
            name='about_species',
            field=models.CharField(default='specific', max_length=1000),
        ),
        migrations.AddField(
            model_name='other_animals',
            name='animal_Description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='other_animals',
            name='animal_History',
            field=models.CharField(default='Sorry we do not have much history on this Animal.', max_length=1000),
        ),
    ]
