# Generated by Django 3.2.10 on 2024-01-26 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_auto_20240125_2243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
