# Generated by Django 3.2.10 on 2024-01-26 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='animal_type',
        ),
    ]
