# Generated by Django 3.2.10 on 2024-01-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_remove_favorites_animal_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal_dog',
            old_name='pet_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='birds',
            old_name='bird_Description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='birds',
            old_name='bird_History',
            new_name='History',
        ),
        migrations.RenameField(
            model_name='cats',
            old_name='cat_Description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='cats',
            old_name='cat_History',
            new_name='History',
        ),
        migrations.RenameField(
            model_name='other_animals',
            old_name='animal_Description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='other_animals',
            old_name='animal_History',
            new_name='History',
        ),
        migrations.RemoveField(
            model_name='other_animals',
            name='about_species',
        ),
    ]
