# Generated by Django 3.2.10 on 2024-01-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20240126_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal_dog',
            old_name='dog_Description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='animal_dog',
            old_name='dog_History',
            new_name='History',
        ),
        migrations.RenameField(
            model_name='birds',
            old_name='bird_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='cats',
            old_name='cat_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='other_animals',
            old_name='animal_id',
            new_name='id',
        ),
    ]
