# Generated by Django 3.2.10 on 2024-01-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_auto_20240126_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal_dog',
            old_name='id',
            new_name='pet_id',
        ),
        migrations.RenameField(
            model_name='birds',
            old_name='id',
            new_name='bird_id',
        ),
        migrations.RenameField(
            model_name='cats',
            old_name='id',
            new_name='cat_id',
        ),
        migrations.RenameField(
            model_name='other_animals',
            old_name='id',
            new_name='animal_id',
        ),
    ]
