# Generated by Django 5.0 on 2024-02-02 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_auto_20240126_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogadoption',
            old_name='country',
            new_name='pet_type',
        ),
        migrations.RemoveField(
            model_name='dogadoption',
            name='zip_code',
        ),
    ]
